### ISSUE TITLE
`--paused` breaks load module

### ISSUE THREAD

**Issue by tolauwae** [TOPLLab/WARDuino#112]

**Comment by carllocos** [comment]
For context: when you start the VM in a `pause` state. Loading the module will fail because in order to load, the VM needs to [run_init_exp](https://github.com/TOPLLab/WARDuino/blob/5bcf4c6a7bff96debb0b1ac677ba558d1d1381fb/src/WARDuino/WARDuino.cpp#L258) which interprets an initial expression. But the VM will not be able to interpret the initial expressions because it is in a paused state.

The solution is to change the VM to a paused state only after the module correctly loads.
