### ISSUE TITLE
`subscribe_interrupt` requires the use of a memory page and table

### ISSUE THREAD

**Issue by carllocos** [TOPLLab/WARDuino#65]
I'm not sure whether this is an issue or not but I rather mention it just in case.

I noticed that to correctly use primitive [subscribe_interrupt](https://github.com/TOPLLab/WARDuino/blob/d97ee71c7c10c14c822349e7e144647b7de9b81c/src/Primitives/arduino.cpp#L520) the executed Wasm needs to use a memory page and provide the function that needs to be used as callback as a table index.

I can understand why we need the memory page since this is the location where MQTT payloads get stored but are we 100% sure that compilers will always generate Wasm that uses at least one memory page? And also is there a reason why we need to pass the callback identifier through the table? Can the function identifier of the callback simply be passed as an argument to `subscribe_interrupt`?

**Comment by tolauwae** [comment]
Let's take those 2 questions in order.

**Memory requirement**
A Wasm program does not initialise memory by default, but only when a memory is declared. Compilers will not generate such declarations if a program does not use linear memory (rarely the case since compilers often use linear memory themselves). So indeed our system requires any program using async events to declare a linear memory. This requirement is due to Wasm only supporting one memory. In a world with multiple memories the `env` module in the WARDuino VM can generate its own memory. So when the [multi-memory proposal](https://github.com/WebAssembly/multi-memory) is standardised this requirement will be relaxed.

**Using the table**
Invoking the callback is formalised as a `call_indirect` to minimise the new elements we added on top of the Wasm spec.
A `call_indirect` always passes through the table. Table references in Wasm are specifically introduced to replace function pointers. So from Wasm perceptive it is most intuitive to pass functions by their table reference.
