### ISSUE TITLE
Fix Schrödinbug: reflashing + incomplete callback synchronisation

### ISSUE THREAD

**Issue by tolauwae** [TOPLLab/WARDuino#74]
OOP doesn't seem to work anymore:

1. Reflashing undoes init code: `set_pinmode`, `subscribe_interrupt`, ... So no events are generated from the device.
2. Callbackmapping only synced when fetching the snapshot. So either (A) the drone can receive events but the emulator has an empty callbackmapping or (B) the drone cannot receive events (_see 1_) while the emulator has a correct callbackmapping.

**Comment by tolauwae** [comment]
Is fixed in [v0.2.1](https://github.com/TOPLLab/WARDuino/tree/v0.2.1).

**Comment by carllocos** [comment]
I think that with commit 0a6dc5f255a19846aff957c355f47df2bc7da73b I removed the code that you were talking about on your second bullet point *"emulator now asks for a callbackmapping dump after each proxy call "*. I figured that asking the callbackmappings was redundant since the vscode plugin already asks for this when setting up for out-of-place debugging. I did not know it was meant to solve an issue that you had.

So you may want to uncomment that portion of code.

**Comment by tolauwae** [comment]
Ok I'll reopen the issue and check if this is broken again.

**Comment by tolauwae** [comment]
Has been fixed in [patch 0.3.1](https://github.com/TOPLLab/WARDuino/releases/tag/v0.3.1).
